//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.LibroService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibroService.ILibroService")]
    public interface ILibroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Add", ReplyAction="http://tempuri.org/ILibroService/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        ML.Result Add(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Add", ReplyAction="http://tempuri.org/ILibroService/AddResponse")]
        System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Update", ReplyAction="http://tempuri.org/ILibroService/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        ML.Result Update(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Update", ReplyAction="http://tempuri.org/ILibroService/UpdateResponse")]
        System.Threading.Tasks.Task<ML.Result> UpdateAsync(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Delete", ReplyAction="http://tempuri.org/ILibroService/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        ML.Result Delete(int IdLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/Delete", ReplyAction="http://tempuri.org/ILibroService/DeleteResponse")]
        System.Threading.Tasks.Task<ML.Result> DeleteAsync(int IdLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetAll", ReplyAction="http://tempuri.org/ILibroService/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        ML.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetAll", ReplyAction="http://tempuri.org/ILibroService/GetAllResponse")]
        System.Threading.Tasks.Task<ML.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetById", ReplyAction="http://tempuri.org/ILibroService/GetByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        ML.Result GetById(int IdLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibroService/GetById", ReplyAction="http://tempuri.org/ILibroService/GetByIdResponse")]
        System.Threading.Tasks.Task<ML.Result> GetByIdAsync(int IdLibro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibroServiceChannel : PL.LibroService.ILibroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibroServiceClient : System.ServiceModel.ClientBase<PL.LibroService.ILibroService>, PL.LibroService.ILibroService {
        
        public LibroServiceClient() {
        }
        
        public LibroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result Add(ML.Libro libro) {
            return base.Channel.Add(libro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Libro libro) {
            return base.Channel.AddAsync(libro);
        }
        
        public ML.Result Update(ML.Libro libro) {
            return base.Channel.Update(libro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UpdateAsync(ML.Libro libro) {
            return base.Channel.UpdateAsync(libro);
        }
        
        public ML.Result Delete(int IdLibro) {
            return base.Channel.Delete(IdLibro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> DeleteAsync(int IdLibro) {
            return base.Channel.DeleteAsync(IdLibro);
        }
        
        public ML.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ML.Result GetById(int IdLibro) {
            return base.Channel.GetById(IdLibro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetByIdAsync(int IdLibro) {
            return base.Channel.GetByIdAsync(IdLibro);
        }
    }
}
